In [ ]:
from local.torch_basics import *
from local.test import *
from local.data.all import *
from local.vision.core import *
from local.notebook.showdoc import *

## `Transform` decorator demo

In [ ]:
source = untar_data(URLs.MNIST_TINY)/'train'
items = get_image_files(source)
fn = items[0]; fn

PosixPath('/Users/yang.zhang/git/fastai_dev/dev/data/mnist_tiny/train/7/9243.png')

In [ ]:
def neg(x): return -x

In [ ]:
neg(3)

-3

In [ ]:
tup = (1,3)
neg(tup)

TypeError: bad operand type for unary -: 'tuple'

In [ ]:
arr = array([1,3])
neg(arr)

array([-1, -3])

- x, y
    - image, pet breed - categorization
    - source image, mask - segmentation
    - (image tuple), bool - siamese
    - (conts, cats), targ = tabular

In [ ]:
@Transform
def neg(x): return -x

In [ ]:
neg(tup)

(-1, -3)

In [ ]:
img = load_image(fn); img

In [ ]:
timg = tensor(array(img)).float()
tsub = timg[12:15]
tsub

tensor([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 157., 162.,  22.,
           0.,   0.,   0.,   0.,  27., 207., 204.,  12.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0., 150., 233.,  88.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   8., 230., 176.,  13.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.]])

In [ ]:
neg(tsub)

tensor([[  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0., -157.,
         -162.,  -22.,   -0.,   -0.,   -0.,   -0.,  -27., -207., -204.,  -12.,
           -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
        [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,
           -0.,   -0.,   -0.,   -0.,   -0.,   -0., -150., -233.,  -88.,   -0.,
           -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
        [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,
           -0.,   -0.,   -0.,   -0.,   -0.,   -8., -230., -176.,  -13.,   -0.,
           -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.]])

In [ ]:
neg((tsub, tsub))

(tensor([[  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0., -157.,
          -162.,  -22.,   -0.,   -0.,   -0.,   -0.,  -27., -207., -204.,  -12.,
            -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
         [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,
            -0.,   -0.,   -0.,   -0.,   -0.,   -0., -150., -233.,  -88.,   -0.,
            -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
         [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,
            -0.,   -0.,   -0.,   -0.,   -0.,   -8., -230., -176.,  -13.,   -0.,
            -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.]]),
 tensor([[  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0., -157.,
          -162.,  -22.,   -0.,   -0.,   -0.,   -0.,  -27., -207., -204.,  -12.,
            -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.],
         [  -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,   -0.,
          

In [ ]:
Transform??

In [ ]:
def norm(x,m,s): return (x-m)/s

In [ ]:
nimg = norm(timg, 127.,50.)
nimg[12:15]

tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400,  0.6000,  0.7000, -2.1000, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.0000,  1.6000,  1.5400, -2.3000, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          0.4600,  2.1200, -0.7800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400],
        [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.3800,
          2.0600,  0.9800, -2.2800, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
         -2.5400, -2.5400, -2.5400, -2.5400]])

In [ ]:
timg.mean(), nimg.mean()

(tensor(15.1709), tensor(-2.2366))

In [ ]:
imgtup = (timg, 1)
imgtup

(tensor([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.],
     

In [ ]:
norm(imgtup, 127.,50.)

TypeError: unsupported operand type(s) for -: 'tuple' and 'float'

In [ ]:
@Transform
def norm(x,m,s): return (x-m)/s

In [ ]:
norm(imgtup, m=127.,s=50.)

(tensor([[-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2.5400],
         [-2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400, -2.5400,
          -2.5400, -2.5400, -2.5400, -2

In [ ]:
@Transform
def norm(x,m,s): return (x-m)/s

In [ ]:
norm(imgtup, m=127.,s=50.)[1]

-2.52

In [ ]:
class MyTensorImg(TensorBase): pass

In [ ]:
mti = MyTensorImg(timg)

In [ ]:
@Transform
def norm(x:MyTensorImg,m,s): return (x-m)/s

In [ ]:
norm(imgtup, m=127.,s=50.)[1]

1

In [ ]:
class MyInt(int): pass

@Transform
def norm(x:MyInt,m,s): return (x-m)/s

mi = MyInt(1)
imgtup = (timg,mi)
norm(imgtup, m=127.,s=50.)[1]

-2.52

In [ ]:
@Transform
def norm(x:int,m,s): return (x-m)/s
imgtup = (timg,1)
norm(imgtup, m=127.,s=50.)[1], norm(imgtup, m=127.,s=50.)[0]

(-2.52,
 tensor([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.

## need state; turn into class

In [ ]:
class Norm(Transform):
    def __init__(self,m,s): 
        super().__init__()
        self.m,self.s = m,s
    def encodes(self, x:Tensor): return (x-self.m)/self.s

m,s = timg.mean(),timg.std()
f = Norm(m=m,s=s)
nimg = f(timg)

In [ ]:
imgtup = (mti,mi)
ttup = f(imgtup)

In [ ]:
@Transform
def flip_img(x:MyTensorImg): return torch.flip(x, 1) if random.random()>0.5 else x

In [ ]:
ttup = flip_img(f(imgtup))

In [ ]:
compose

<function local.core.compose(*funcs, order=None)>

In [ ]:
pipe = compose(f, flip_img)
ttup = pipe(imgtup)

TypeError: flip(): argument 'dims' (position 2) must be tuple of ints, not int

In [ ]:
pipe = Pipeline([f, flip_img])
ttup = pipe(imgtup)